spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: parth24.todankar@gmail.com
    password: Diamondcats
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true