spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:pos_temp}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: parth24.todankar@gmail.com
    password: Diamondcats
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

server:
  port: 5001

razorpay:
  api:
    key: your razorpay key
    secret: provide yor razorpay secrate



stripe:
  api:
    key: provide your stripe api key

gemini:
  api:
    key: provide your gemin api key optional

app:
  frontend:
    reset-url: http://localhost:5173/auth/reset-password?token=

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
